import { Link } from 'react-router-dom';

/**
 * Landing page.
 * Hero at the top, then scroll to see the call-to-action and more information.
 */
export default function Home() {
  return (
    <main className="home-page">
      <section className="home-hero">
        <p className="home-hero-kicker">Early learning assessment</p>
        <h1 className="home-hero-title">AI Learning Screening</h1>
        <p className="home-hero-subtitle">
          A short, structured screening tool that combines handwriting, speech, and cognitive
          tasks to help flag potential learning difficulties early.
        </p>
        <div className="home-scroll-hint">
          <span>
            Scroll down to begin the assessment
            <span className="home-scroll-hint-arrow">↓</span>
          </span>
        </div>
      </section>

      <section className="home-section" id="start">
        <h2>Begin assessment</h2>
        <p>
          When you&apos;re ready, start the guided flow. You can move step-by-step and return
          to this page at any time.
        </p>
        <Link to="/user">
          <button type="button" className="btn-primary">
            Start assessment
          </button>
        </Link>
      </section>

      <section className="home-section">
        <h2>What this tool does</h2>
        <p>
          This prototype is designed for research and educational purposes. It does not provide
          a diagnosis, but it can highlight patterns that may warrant further professional
          evaluation.
        </p>
        <ul className="home-section-list">
          <li>Collects basic background information.</li>
          <li>Analyzes handwriting and spoken language samples via backend models.</li>
          <li>Measures simple reaction timing in a short cognitive task.</li>
        </ul>
      </section>

      <section className="home-section">
        <h2>How the assessment works</h2>
        <ul className="home-section-list">
          <li>User info: name, age, and consent to participate.</li>
          <li>Handwriting: upload an image of a handwriting sample.</li>
          <li>Speech: read a short prompt aloud and record audio.</li>
          <li>Eye tracking: placeholder step for a future gaze-tracking module.</li>
          <li>Cognitive: simple reaction-time test.</li>
          <li>
            Report: see risk scores from each module and a combined final summary generated by
            the backend.
          </li>
        </ul>
      </section>
    </main>
  );
}
